[package]
name = "file_encryption_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
rand = "0.8"  # Ensure the `rand` library is included if using random key generation
